# ===========================================
# Emacs-like Keymap
# ===========================================

[normal]

# Cursor
ctrl+F           : moveRight
ctrl+B           : moveLeft
ctrl+N           : moveDown
ctrl+P           : moveUp
opt+F            : moveWordRight
opt+B            : moveWordLeft
ctrl+A           : moveToBeginningOfParagraph
ctrl+E           : moveToEndOfParagraph

ctrl+X, H        : selectAll

ctrl+<semicolon> : performGridJump

# Edit
ctrl+D           : deleteForward
ctrl+H           : deleteBackward
opt+D            : deleteWordForward
opt+<backspace>  : deleteWordBackward
ctrl+K           : deleteToEndOfParagraph
ctrl+W           : cut
ctrl+Y           : yank
opt+Y            : yankPop
opt+W            : copy
ctrl+-           : undo
ctrl+/           : undo

ctrl+X, ctrl+O   : removeEmptyLines

# Case conversion
# In original Emacs, if the caret is located within a word, 
# only the portion of the word to the right of the caret 
# is treated as the target of capitalize, uppercase, and 
# lowercase operations.
# In Ganpi, by contrast, those operations apply to the entire 
# word containing the caret.
opt+C            : capitalizeWord, moveToEndOfSelection
opt+U            : uppercaseWord, moveToEndOfSelection
opt+L            : lowercaseWord, moveToEndOfSelection

# Scroll
ctrl+V           : pageDown
opt+V            : pageUp
ctrl+L           : centerSelectionInVisibleArea

# Jump
ctrl+X, ctrl+P   : jumpBackwardInHistory
ctrl+X, ctrl+N   : jumpForwardInHistory

# Completion
opt+/            : setCompletionModeOn

# View
ctrl+X, 0        : focusForwardTextView

# Buffer, File treatment
opt+<space>      : setMarkedModeOn
ctrl+G           : setMarkedModeOff, setCompletionModeOff
ctrl+S           : searchNextAction
ctrl+R           : searchPrevAction

ctrl+X, ctrl+S   : saveDocument
ctrl+X, ctrl+W   : saveDocumentAs
ctrl+X, ctrl+C   : terminate
ctrl+X, K        : performClose
ctrl+X, ctrl+F   : openDocument

opt+shift+5      : showSubstituteCommandLineAction
