# ===========================================
# Emacs-like Keymap
# ===========================================

[normal]

# Cursor
ctrl+F           : moveRight
ctrl+B           : moveLeft
ctrl+N           : moveDown
ctrl+P           : moveUp
opt+F            : moveWordRight
opt+B            : moveWordLeft
ctrl+A           : moveToBeginningOfParagraph
ctrl+E           : moveToEndOfParagraph

ctrl+X, H        : selectAll

ctrl+<semicolon> : performGridJump

# Edit
ctrl+D           : deleteForward
ctrl+H           : deleteBackward
opt+D            : deleteWordForward
opt+<backspace>  : deleteWordBackward
ctrl+K           : deleteToEndOfParagraph
ctrl+W           : cut
ctrl+Y           : yank
opt+Y            : yankPop
opt+W            : copy
ctrl+-           : undo
ctrl+/           : undo

ctrl+X, ctrl+O   : removeEmptyLines

# Repeating
# In Ganpi, Ctrl+U does not work by itself to repeat a command four
# times as it does in Emacs; a numeric argument must always be entered.
ctrl+U           : beginRepeatCountInput

# Case conversion
opt+C            : capitalizeWordToEndOfWord, moveToEndOfSelection
opt+U            : uppercaseWordToEndOfWord, moveToEndOfSelection
opt+L            : lowercaseWordToEndOfWord, moveToEndOfSelection

# Scroll
ctrl+V           : pageDown
opt+V            : pageUp
ctrl+L           : centerSelectionInVisibleArea

# Jump
ctrl+X, ctrl+P   : jumpBackwardInHistory
ctrl+X, ctrl+N   : jumpForwardInHistory

# Completion
opt+/            : setCompletionModeOn

# View
ctrl+X, 0        : focusForwardTextView

# Buffer, File treatment
opt+<space>      : setMarkedModeOn
ctrl+G           : setMarkedModeOff, setCompletionModeOff
ctrl+S           : searchNextAction
ctrl+R           : searchPrevAction

ctrl+X, ctrl+S   : saveDocument
ctrl+X, ctrl+W   : saveDocumentAs
ctrl+X, ctrl+C   : terminate
ctrl+X, K        : performClose
ctrl+X, ctrl+F   : openDocument

opt+shift+5      : showSubstituteCommandLineAction
