##
## Ganpi defaults
##

[system]
# アプリケーション全体の設定。

# ファイルを開く際にファイルタイプを検出してそれに合わせた言語設定にするか否か。(true|false)
.auto_detection.file_type                : true


[document]
# ドキュメント単位の設定。

# 新規ドキュメントのウインドウサイズ設定。幅(width)と高さ(height)を個別に指定する。ピクセル単位。
.size.width                              : 600.0
.size.height                             : 600.0

# 新規ドキュメントの改行コードを設定。(lf|cr|crlf)
.newline                                 : lf

# 新規ドキュメントの文字コードを設定。(utf8|utf16|utf32|sjis|jis|euc)
.character_code                          : utf8

# 新規ドキュメントのファイルタイプを設定。
# (plain|ruby|html|php|ini|sh|python|typescript|css|yaml|json|yamaha|cisco|log)
.file_type                               : plain

# 行番号を表示するか否か。 (true|false)
.show_line_number                        : true

# ドキュメントへのフォント情報のドロップで表示フォントの変更を拒否するか否か。(true|false)
.reject_font_change                      : false


[editor]
# キーアサインを設定。(ganpi|vi|emacs|system)
# systemはOS標準のキーアサインでemacsに近い。ただし2ストローク以上のアサインはない。
.key_assign                              : ganpi

# edit mode (normal/editモード切替機能)を利用するか否か。(true|false)
.use_edit_mode                           : true

# edit mode (編集専用モード)をどのモードで開始するか。(normal|edit)
# vi風が好みの場合にはeditを選択した方が自然。
# (ganpiでは文字入力状態をnormal、編集のみのモードをeditと呼称する。)
.edit_mode                               : normal

# yank pop を利用するか否か。(true|false)
# yank popはpaste(yank)動作後に所定の指示を出すとcopyの履歴を辿って挿入する機能。
.use_yank_pop                            : true

# 語彙補完を利用するか否か。(true|false)
.use_word_completion                     : true

# 語彙補完の際に候補語彙のメニューを出すか否か。(true|false)
.show_completion_menu                    : true


[search_window]
# 検索パネルの設定。

# 検索文字列のフォントサイズ・フォントファミリーを指定する。
# フォントサイズはpt単位。12.0 のように記述する。
# フォントファミリーは正確な記述が必要。
# メニュー「Option/Show Font Panel...」で表示されるパネルから選択すると挿入される。(サイズは削除で)
.search_field.font.size                  : 14.0
.search_field.font.family                : ?

# 置換文字列のフォントサイズ・フォントファミリーを指定する。
.replace_field.font.size                 : 14.0
.replace_field.font.family               : ?

# 「Search」ボタンを押下後にパネルを隠すか否か。(true|false)
.close_when_done                         : true


[color_panel]
# カラーパネルの設定。

# アルファを表示するか否か。(true|false)
# カラーパネルを呼び出す際に、optionキーを押下しておくと設定と逆の表示になる。
.with_alpha                              : false


[parser.base]
# シンタックスモード全体の共通設定。
# 個別の設定によって上書きされる。

# タブ幅を設定。(整数)
# 文頭の連続するタブについて、空白文字の何倍の幅で表示するか指定する。
.tab_width                               : 4

# 行間を設定。(float)
.line_spacing                            : 2.0

# 行の折り返しをするか否か。(true|false)
.word_wrap                               : true

# オートインデントをするか否か。(true|false)
.auto_indent                             : true

# 機能文字(不可視文字)を表示するか否か。(true|false)
.show.invisibles                         : false

# 折り返し行の開始位置をどこにするか設定。
# (none|same|1tab|1.5tab|2tab)
.wrapline_offset                         : same

# インデントの際にタブではなく空白文字を使用するか否か。(true|false)
.indent_using_spaces                     : true

# 機能文字(不可視文字)それぞれについて、表示するか否か。(true|false)
# .show.invisiblesがtrueの場合に反映される。
.show.invisibles.tab                     : true
.show.invisibles.newline                 : true
.show.invisibles.space                   : true
.show.invisibles.fullwidth_space         : true

# 機能文字(不可視文字)
# ⏎ ➤ ∙ □
.invisibles.glyph.newline                : ⏎
.invisibles.glyph.tab                    : ➤
.invisibles.glyph.space                  : ∙
.invisibles.glyph.fullwidth_space        : □

# シンタックスモードの色指定。
# macOSの外観モードのLightとDarkのそれぞれについて指定する。
# .text: ベース文字, .background: 背景
# .literal: クオート・正規表現などのリテラル, .comment: コメント
# .variable: 変数, .keyword: キーワード, .numeric: 数値
# .tag: HTMLなどのタグ
# .invisibles: 機能文字(不可視文字), completion: 補完機能の補完部分
# .selection_highlight.active: 選択部分(アクティブ)
# .selection_highlight.inactive: 選択部分(インアクティブ)

# Light (無銘)
.color.text                              : #1E1E1E
.color.background                        : #FAFAFA
.color.literal                           : #860300
.color.comment                           : #0B5A00
.color.variable                          : #653F00
.color.keyword                           : #070093
.color.numeric                           : #873000
.color.tag                               : #6A6AD4
.color.invisibles                        : #CCCCCC
.color.completion                        : #CCCCCC
.color.selection_highlight.active        : #CCE0FF
.color.selection_highlight.inactive      : #E5E5E5


# Dark (推奨配色)
.color.text.dark                         : #E6E6E6
.color.background.dark                   : #1E1E1E
.color.literal.dark                      : #FF8660
.color.comment.dark                      : #00A34A
.color.variable.dark                     : #E0A050
.color.keyword.dark                      : #85A4FF
.color.numeric.dark                      : #E0A050
.color.tag.dark                          : #6A6AD4
.color.invisibles.dark                   : #555555
.color.completion.dark                   : #777777
.color.selection_highlight.active.dark   : #204080
.color.selection_highlight.inactive.dark : #303030

# Font
# 文書全体で共通して使われるフォントサイズとフォントファミリー
.font.family                             : ?
.font.size                               : 14.0


[parser.html]
# HTMLシンタックス用のみ個別に指定。
.color.keyword                           : #070093
.color.literal                           : #010C7E
.color.numeric                           : #873000
.color.comment                           : #A20000
.color.tag                               : #6A6AD4

.color.keyword.dark                      : #85A4FF
.color.literal.dark                      : #85A4FF
.color.numeric.dark                      : #E0A050
.color.comment.dark                      : #FF6B6B
.color.tag.dark                          : #6A6AD4


